config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :categories, only: %i[index show]
  resources :favourites, only: %i[index create destroy]
  get 'my_profile', to: 'my_profile#show'
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :category
  has_many :bookmarks, dependent: :destroy
  has_many :countries, through: :bookmarks
  has_one_attached :photo
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :country
  belongs_to :application
  has_one :favourite
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :applications, dependent: :destroy
  has_one_attached :photo
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_one_attached :flag

    def full_name
      country = ISO3166::Country[name]
      country.translations[I18n.locale.to_s] || country.common_name || country.iso_short_name
    end
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :bookmark
  belongs_to :user

  validates_uniqueness_of :user, scope: [:bookmark]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favourites, dependent: :destroy
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show]

  def index
    @categories = Category.all
    @country = Country.find_by(name: params[:country])
  end

  def show
    category = Category.find(params[:id])
    country = Country.find_by(name: params[:format])
    @bookmarks = Bookmark.joins(:application)
                         .where(country: country)
                         .where("applications.category_id = #{category.id}")
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_favourite, only: %i[destroy]

  def index
    @favourites = current_user.favourites
  end

  def create
    @favourite = Favourite.new(favourite_params)
    @favourite.user = current_user
    @favourite.save
  end

  def destroy
    @favourite.destroy
    redirect_to favourites_path, status: :see_other
  end

  private

  def set_favourite
    @favourite = Favourite.find(params[:id])
  end

  def favourite_params
    params.permit(:bookmark_id)
  end
end

app/controllers/my_profile_controller.rb
class MyProfileController < ApplicationController
  def show
    @favourites = Favourite.where(user: current_user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def my_profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_app.html.erb
<div class="col-12 mb-3">
  <div class="container shadow rounded-4 py-2 listingcard">
    <button type="button" class="dropdown">
      <%= cl_image_tag bookmark.application.photo.key %>
      <h2><%= bookmark.application.name %></h2>
    </button>
    <div class="content">
      <p><%= bookmark.application.description %></p>
      <div class="d-flex justify-content-between">
        <% if Favourite.find_by(bookmark: bookmark) %>
          <% if controller_name=="favourites" %>
            <%= link_to favourite_path(favourite), data: { turbo_method: "delete" }, class: "no-text-decoration" do %>
              <p class="m-0 favourite-remove" style="line-height: 35px"><strong><i class="fa-solid fa-circle-minus"></i> Remove</strong></p>
            <% end %>
          <% else %>
            <i class="fa-solid fa-heart"></i>
          <% end %>
        <% else %>
          <%= link_to favourites_path(bookmark_id: bookmark), data: { turbo_method: "post" }, class: "favourite-btn"  do %>
            <i class="fa-regular fa-heart"></i>
          <% end %>
        <% end %>
        <div class="links">
          <%= link_to bookmark.application.appstore do %>
            <%= image_tag "apple.jpg" %>
          <% end %>
          <%= link_to bookmark.application.playstore do %>
            <%= image_tag "play.jpg" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<head>
  <link rel="stylesheet" href="_category.scss">
</head>


  <div class="col-6">
    <div class="shadow rounded-4 mb-4 d-flex fs-md-3 fs-sm-4">
      <a href="#"
        class="text-black flex-grow-1 d-flex flex-row align-items-center text-decoration-none px-4 py-3">
        <span class="me-3" style="font-size:2em"><%= icon %></span>
          <div class="card-product-infos">
          <strong class=""><%= title %></strong>
        </div>
      </a>
    </div>
  </div>

app/views/categories/_categorycard.html.erb
<div class="text-center category-img">

  <div style="background-image: linear-gradient(rgb(0 0 0 / 39%), rgb(49 111 173 / 52%)), url('<%= cl_image_path category.photo.key %>')" class="category-card__bg-img">
  </div>
  <div class="shadow rounded-4 d-flex fs-md-3 fs-sm-4 categories-cards">
    <%= link_to category_path(category, country), class: "text-black flex-grow-1 d-flex flex-row align-items-center text-decoration-none justify-content-center" do %>
      <div class="card-product-infos">
        <strong class="title blurred opacity"><%= title %></strong>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="home-banner rounded-4 position-relative mt-5">
  <%= image_tag "pngegg.png", class: "d-block bg-image rounded-4 card-phone position-absolute"%>
  <div class="banner-content">
    <% if @country.present? %>
      <div>
        <h1 class="mb-0">Welcome to</h1>
        <h2 class="mb-0"><%= session[:country_name] %>!</h2>
        <%= cl_image_tag @country.flag.key, class: "country-flag" %>
      </div>
    <% else %>
      <div>
        <h1 class="mb-0">Welcome!</h1>
        <p class="m-0">Select a country to start.</p>
      </div>
    <% end %>
  </div>
</div>


<div class="search-bar">
  <%= render 'shared/search' %>
</div>

<div class="row categories-grid__container">
    <ul data-search-country-target="country" style="list-style: none;" class="categories-grid">
      <% @categories.each do |category|%>
        <li><%= render 'categorycard', icon: category.icon, title: category.name, category: category, country: session[:country] %></li>
      <% end %>
    </ul>
</div>

app/views/categories/show.html.erb
<div class="show-banner rounded-4 position-relative" style="padding: 40px;">
  <h1 class="text-center pb-4 cat-name"><%= @category.name %></h1>
</div>
<% if @bookmarks.empty? %>
  <h5 class="alert alert-warning">Applications are going to be added soon!</h5>
<% else %>
  <% @bookmarks.each do |bookmark| %>
    <%= render 'app', bookmark: bookmark %>
  <% end %>
<% end %>

<div class="col-md-12 text-center" style="padding: 30px;">
  <%= link_to "Back", :back, class: "btn btn-back" %>
</div>

<div class='favorites-notice'>
</div>

app/views/favourites/_favouritescard.html.erb
  <%# <div class="col-md-12 text-center my-2 mx-4">
    <div class="shadow rounded-4 mb-4 d-flex fs-md-3 fs-sm-4">
      <%= link_to 'favourites/favouritesapps', class: "text-black flex-grow-1 d-flex flex-row align-items-center text-decoration-none px-4 py-4" do %>
        <%# <span class="me-3" style="font-size:2em">🇩🇪</span>
          <div class="card-product-infos">
          <strong class="title">Germany</strong>
        </div>
      <% end %>
    <%# </div>
  </div> %>
<% @favourites.group_by {|f| f.bookmark.country}.each do |country|%>
  <div class="container rounded-4 py-2 favourites-card">
      <button type="button" class="dropdown">
          <h1 class="country-drop" >
          <h1 class="country-icon">
          <%# <%= "🇵🇹" if country.first.full_name == "Portugal" %>
          <%# <%= "🇩🇪" if country.first.full_name == "Germany" %>
          </h1>
          <h1 class="country-name">
            <%= country.first.full_name %>
          </h1>
          </h1>
      </button>
      <div>
        <% country.second.each do |favourite|%>
        <%= render "categories/app", bookmark: favourite.bookmark, favourite: favourite %>
      <% end %>
      </div>
  </div>
  <br>
<% end %>

app/views/favourites/index.html.erb
<div class="show-banner rounded-4 position-relative" style="padding: 40px;">
  <h1 class="text-center pb-4 fav-name">Favourites</h1>
</div>

 <%= render 'favourites/favouritescard' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LinkLocal</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if controller_name != "pages" || action_name =! "home" %>
      <%= render "shared/navbar" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/my_profile/show.html.erb
<div class='profile-bg'>
  <div class='d-flex justify-content-center pt-5'>
    <%= cl_image_tag current_user.photo.key, class: "profile-img" %>
  </div>
  <h3 class="text-center mt-2 mb-3"><%= "#{current_user.first_name} #{current_user.last_name}" %></h3>
  <p class="profile-info"><i class="fa-solid fa-envelope"></i> <%= current_user.email %></p>

 <div>
    <%= link_to "Favourites", favourites_path, class: "btn btn-primary rounded-4 profile-link mt-4" %>
  </div>

<br>

  <div>
    <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-light rounded-4 profile-link mt-4" %>
    <%= link_to "Sign Out", edit_user_registration_path, class: "profile-link text-center no-text-decoration my-3" %>
  </div>

  <br>

  <%# <h2 class="text-center mt-5 mb-4">❤️ My Favourites</h2>
  <div class="favourites-cards">
    <% @favourites.each do |favourite| %>
      <%# <%= render "categories/app", bookmark: favourite.bookmark, favourite: favourite %>
    <%# <% end %>
  <%# </div> %>
</div>

app/views/pages/home.html.erb
<%= video_tag "landing.mp4", autoplay: true, loop: true, muted: true, playsinline: true, class: "home_video" %>
<div class="col-md-12 text-center text-white">
  <div class="home-page" style="">
    <div class="home-page__top">
      <%= image_tag "Logo4.jpg", class: "home-page__logo" %>
    </div>
    <div class="home-page__text">
      <h2>Find the apps used by locals.</h2>
    </div>
  </div>
</div>

<div class="home-page__search-bar">
  <%= render 'shared/search' %>
</div>

<div class="home-page__buttons">
  <div class="create-button">
    <%= link_to "Create account", new_user_registration_path, class: "btn btn-flat" %>
  </div>
  <% if current_user %>
    <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: "delete" }, class: "text-white" %>
  <% else %>
    <%= link_to "Sign In", new_user_session_path, class: "text-white" %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-light text-center text-lg-start">
  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
    </div>
    <div class="footer-copyright">
      @copyright LinkLocal<i class=></i>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark mx-3">
  <div class=" white-bg d-flex justify-content-space-between align-items-center">
    <div>
      <%= link_to categories_path, class: "home-page__logo" do %>
        <i class="fa-solid fa-house p-1"></i>
      <% end %>
    </div>

      <%= link_to root_path, class: 'd-block text-center' do %>
        <%= image_tag "Logo1.jpg", class: "logo" %>
      <% end %>

    <div id="menuToggle">
    <!--
    A fake / hidden checkbox is used as click reciever,
    so you can use the :checked selector on it.
    -->
    <input type="checkbox">

    <!--
    Some spans to act as a hamburger.

    They are acting like a real hamburger,
    not that McDonalds stuff.
    -->
    <span></span>
    <span></span>
    <span></span>

    <!--
    Too bad the menu has to be inside of the button
    but hey, it's pure CSS magic.
    -->
    <ul id="menu">
      <% if current_user %>
          <li><%= link_to "Profile", my_profile_path, class: "navbar-link" %></li>
          <li><%= link_to "Favourites", favourites_path, class: "navbar-link" %></li>
       <% else %>
          <li><%= link_to "Log in", new_user_session_path, class: "navbar-link" %></li>
       <% end %>
    </ul>
    </div>
    </div>
  </div>
</nav>
<br>

<%# <button class="menuToggle" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
       <%# <input type="checkbox" /> %>
      <%# <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
      <div class="d-flex justify-content-around text-align-center">
      <ul id="menu">
        <% if current_user %>
          <%# <li><%= link_to "Saved Apps", favourites_path, class: "navbar-link" %></li>
          <%# <li><%= link_to "My Profile", my_profile_path, class: "navbar-link" %></li>
        <%# <% else %>
          <%# <li><%= link_to "Log in", new_user_session_path, class: "navbar-link" %></li>
        <%# <% end %>

app/views/shared/_search.html.erb
<div class="btn-group mx-auto">
  <div class="position-relative">
    <%= form_with url: categories_path, method: :get do %>
      <%= country_select(nil, :country,
        {
          priority_countries: ["DE", "PT", "GB"],
          selected: session[:country],
          include_blank: 'Select a country'
        },
        {
          class: "form-control rounded-4 bg-white",
          data: { controller: "dropdown-submit", action: "change->dropdown-submit#change" },
        })
      %>
      <div class="position-absolute magnifier">
        <i class="fa-solid fa-solid fa-location-dot text-secondary"></i>
      </div>
    <% end %>
  </div>
</div>

app/views/users/my_profile.html.erb
<br><br>
<div class="container-fluid well span6">
	<div class="row-fluid">
        <div class="span2" >
		    <img src="https://secure.gravatar.com/avatar/de9b11d0f9c0569ba917393ed5e5b3ab?s=140&r=g&d=mm" class="img-circle">
        </div>

        <div class="span8">
            <h3>User Name</h3>
            <h6>Email: MyEmail@servidor.com</h6>
            <h6>Ubication: Colombia</h6>
            <h6>Old: 1 Year</h6>
            <h6><a href="#">More... </a></h6>
        </div>

        <div class="span2">
            <div class="btn-group">
                <a class="btn dropdown-toggle btn-info" data-toggle="dropdown" href="#">
                    Action
                    <span class="icon-cog icon-white"></span><span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="#"><span class="icon-wrench"></span> Modify</a></li>
                    <li><a href="#"><span class="icon-trash"></span> Delete</a></li>
                </ul>
            </div>
        </div>
</div>
</div>